language: node_js
sudo: false
node_js:
- 0.12
install:
- npm install
- "./node_modules/.bin/bower update"
script: npm run build
cache:
  directories:
  - node_modules
  - bower_components
after_success:
- "./scripts/travis_deploy"
